server:
  port: 8080
github:
  client:
    id: c71a34b30bf116efe29b
    secret: 46bf3b8743eaf30994f5c02970112ff1bb99b532
    uri: http://localhost:8080/callback
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  devtools:
    livereload:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml
